image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - felixfbecker.php-debug # Add this for PHP debugging
ports:
  - port: 80 # Web server port
    onOpen: "open-browser"
  - port: 3306 # MySQL port
    onOpen: "open-browser"

tasks:
  - name: Install Gitpod CLI
    command: sudo apt update && sudo apt install -y gitpod-cli
        