image:
  file: .gitpod.Dockerfile

ports:
  - name: application
    port: 80
    onOpen: open-preview
  - name: database
    port: 3306
    onOpen: ignore # If you're running MySQL in a Docker container