image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - felixfbecker.php-debug # Add this for PHP debugging
ports:
  - port: 80 # Web server port
    onOpen: forward
  - port: 3306 # MySQL port
    onOpen: forward